# Form implementation generated from reading ui file 'Application_Qt_module_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 673)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("resources/icon.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(
            "#MainWindow\n"
            "{\n"
            "border-image: url(resources/Background4.jpg);\n"
            "background-position: center center no-repeat  fixed;\n"
            "background-size: 100% 100%;\n"
            "\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            ""
        )
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet(
            "#centralwidget {background-color: transparent;}"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.verticalGroupBox.setAcceptDrops(False)
        self.verticalGroupBox.setAutoFillBackground(False)
        self.verticalGroupBox.setStyleSheet(
            "#verticalGroupBox {\n"
            "border: 1px inset #10f04f;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.verticalGroupBox.setFlat(False)
        self.verticalGroupBox.setCheckable(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.horizontalWidget = QtWidgets.QWidget(parent=self.verticalGroupBox)
        self.horizontalWidget.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.NoContextMenu
        )
        self.horizontalWidget.setStyleSheet(
            "#horizontalGroupBox {\n" "border: 1px inset #10f04f;\n" "}"
        )
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PlaceForFotos = QtWidgets.QLabel(parent=self.horizontalWidget)
        self.PlaceForFotos.setStyleSheet(
            "#PlaceForFotos\n" "{\n" "border: 4px inset #10f0ad;\n" "\n" "}"
        )
        self.PlaceForFotos.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.PlaceForFotos.setObjectName("PlaceForFotos")
        self.horizontalLayout.addWidget(self.PlaceForFotos)
        self.PlaceForPromFotos = QtWidgets.QLabel(parent=self.horizontalWidget)
        self.PlaceForPromFotos.setStyleSheet(
            "#PlaceForPromFotos\n" "{\n" "border: 4px outset #10f0e9;\n" "\n" "}"
        )
        self.PlaceForPromFotos.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.PlaceForPromFotos.setObjectName("PlaceForPromFotos")
        self.horizontalLayout.addWidget(self.PlaceForPromFotos)
        self.vboxlayout.addWidget(self.horizontalWidget)
        self.gridGroupBox = QtWidgets.QGroupBox(parent=self.verticalGroupBox)
        self.gridGroupBox.setMaximumSize(QtCore.QSize(16777215, 170))
        self.gridGroupBox.setStyleSheet(
            "#gridGroupBox {\n"
            "                width: 100px;\n"
            "                height:100px;\n"
            "                border: 3px solid #1071f0;\n"
            "                border-radius: 15px;\n"
            "}"
        )
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setContentsMargins(9, 3, 5, 2)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSeg = QtWidgets.QPushButton(parent=self.gridGroupBox)
        self.pushButtonSeg.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonSeg.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonSeg.setObjectName("pushButtonSeg")
        self.gridLayout.addWidget(self.pushButtonSeg, 1, 0, 1, 1)
        self.pushButtonStart = QtWidgets.QPushButton(parent=self.gridGroupBox)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonStart.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.gridLayout.addWidget(self.pushButtonStart, 0, 0, 1, 1)
        self.checkBoxSave = QtWidgets.QCheckBox(parent=self.gridGroupBox)
        self.checkBoxSave.setStyleSheet("background: rgba(204, 224, 232, 0.5)")
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.gridLayout.addWidget(self.checkBoxSave, 4, 0, 1, 1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(parent=self.gridGroupBox)
        self.verticalGroupBox_2.setMouseTracking(False)
        self.verticalGroupBox_2.setTabletTracking(False)
        self.verticalGroupBox_2.setAcceptDrops(False)
        self.verticalGroupBox_2.setAutoFillBackground(False)
        self.verticalGroupBox_2.setStyleSheet(
            "#verticalGroupBox_2 {\n"
            "border: 1px inset #1071f0;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.verticalGroupBox_2.setTitle("")
        self.verticalGroupBox_2.setFlat(False)
        self.verticalGroupBox_2.setCheckable(False)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalGroupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DataLabel = QtWidgets.QLabel(parent=self.verticalGroupBox_2)
        self.DataLabel.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DataLabel.setFont(font)
        self.DataLabel.setAutoFillBackground(False)
        self.DataLabel.setStyleSheet("")
        self.DataLabel.setText("")
        self.DataLabel.setObjectName("DataLabel")
        self.horizontalLayout_3.addWidget(self.DataLabel)
        self.SelectionList = QtWidgets.QListWidget(parent=self.verticalGroupBox_2)
        self.SelectionList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SelectionList.setStyleSheet(
            "#SelectionList\n"
            "{\n"
            "border: 4px rgba(204, 224, 232, 0.5);\n"
            "background: rgba(204, 224, 232, 0.5);\n"
            "}"
        )
        self.SelectionList.setObjectName("SelectionList")
        self.horizontalLayout_3.addWidget(self.SelectionList)
        self.SelectionTable = QtWidgets.QTableWidget(parent=self.verticalGroupBox_2)
        self.SelectionTable.setAcceptDrops(False)
        self.SelectionTable.setStyleSheet(
            "#SelectionTable\n"
            "{\n"
            "border: 4px rgba(204, 224, 232, 0.5);\n"
            "background: rgba(204, 224, 232, 0.5);\n"
            "}\n"
            "QHeaderView::section {\n"
            "background-color: rgba(204, 224, 232, 0.5);\n"
            " }"
        )
        self.SelectionTable.setRowCount(0)
        self.SelectionTable.setColumnCount(6)
        self.SelectionTable.setObjectName("SelectionTable")
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(5, item)
        self.SelectionTable.horizontalHeader().setCascadingSectionResizes(False)
        self.SelectionTable.horizontalHeader().setDefaultSectionSize(90)
        self.SelectionTable.horizontalHeader().setHighlightSections(True)
        self.SelectionTable.horizontalHeader().setSortIndicatorShown(False)
        self.SelectionTable.horizontalHeader().setStretchLastSection(True)
        self.SelectionTable.verticalHeader().setCascadingSectionResizes(False)
        self.SelectionTable.verticalHeader().setHighlightSections(True)
        self.horizontalLayout_3.addWidget(self.SelectionTable)
        self.gridLayout.addWidget(self.verticalGroupBox_2, 0, 1, 10, 1)
        self.horizontalWidget_2 = QtWidgets.QWidget(parent=self.gridGroupBox)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalWidget_2.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.PreventContextMenu
        )
        self.horizontalWidget_2.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.horizontalWidget_2.setAutoFillBackground(False)
        self.horizontalWidget_2.setStyleSheet(
            "#horizontalGroupBox_2{           \n" "outline: none;\n" "}"
        )
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelStart = QtWidgets.QLabel(parent=self.horizontalWidget_2)
        self.labelStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelStart.setStyleSheet("#labelStart{ color: white; }")
        self.labelStart.setObjectName("labelStart")
        self.horizontalLayout_2.addWidget(self.labelStart)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.horizontalWidget_2)
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setTabletTracking(False)
        self.horizontalSlider.setAcceptDrops(False)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(25)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.gridLayout.addWidget(self.horizontalWidget_2, 5, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.gridGroupBox)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonSave.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 2, 0, 1, 1)
        self.checkBoxSeg = QtWidgets.QCheckBox(parent=self.gridGroupBox)
        self.checkBoxSeg.setStyleSheet(
            "\n" "background: rgba(204, 224, 232, 0.5)\n" "\n" "\n" ""
        )
        self.checkBoxSeg.setObjectName("checkBoxSeg")
        self.gridLayout.addWidget(self.checkBoxSeg, 3, 0, 1, 1)
        self.vboxlayout.addWidget(self.gridGroupBox)
        self.verticalLayout.addWidget(self.verticalGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FISH data processing"))
        self.PlaceForFotos.setText(
            _translate(
                "MainWindow", "Исходное изображение, в формате .jpeg, png или .czi"
            )
        )
        self.PlaceForPromFotos.setText(
            _translate("MainWindow", "Результат сегментации")
        )
        self.pushButtonSeg.setText(_translate("MainWindow", "Cегментировать"))
        self.pushButtonStart.setText(_translate("MainWindow", "Выбрать фото"))
        self.checkBoxSave.setText(_translate("MainWindow", "Сохранить все"))
        item = self.SelectionTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер клетки"))
        item = self.SelectionTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Центр X"))
        item = self.SelectionTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Центр Y"))
        item = self.SelectionTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Зеленые х-мы"))
        item = self.SelectionTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Красные х-мы"))
        item = self.SelectionTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Тип клетки"))
        self.labelStart.setText(_translate("MainWindow", "Порог точности:  "))
        self.pushButtonSave.setText(_translate("MainWindow", "Сохранить"))
        self.checkBoxSeg.setText(_translate("MainWindow", "Сегментировать все"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
