# Form implementation generated from reading ui file 'Application_Qt_module_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ClickableLabel import ClickableLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 772)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("resources/icon.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(
            "#MainWindow\n"
            "{\n"
            "border-image: url(resources/Background4.jpg);\n"
            "background-position: center center no-repeat  fixed;\n"
            "background-size: 100% 100%;\n"
            "\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            ""
        )
        self.CentralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.CentralWidget.setStyleSheet(
            "#CentralWidget {background-color: transparent;}"
        )
        self.CentralWidget.setObjectName("CentralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CentralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CentralGroupBox = QtWidgets.QGroupBox(parent=self.CentralWidget)
        self.CentralGroupBox.setAcceptDrops(False)
        self.CentralGroupBox.setStyleSheet(
            "#CentralGroupBox {\n" "border: 3px inset #94D9DC;\n" "}"
        )
        self.CentralGroupBox.setObjectName("CentralGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CentralGroupBox)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Sec2_ToolsWidget = QtWidgets.QWidget(parent=self.CentralGroupBox)
        self.Sec2_ToolsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Sec2_ToolsWidget.setStyleSheet("")
        self.Sec2_ToolsWidget.setObjectName("Sec2_ToolsWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Sec2_ToolsWidget)
        self.verticalLayout_5.setContentsMargins(0, 1, 0, 0)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SelectionTable = QtWidgets.QTableWidget(parent=self.Sec2_ToolsWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SelectionTable.setFont(font)
        self.SelectionTable.setAcceptDrops(False)
        self.SelectionTable.setStyleSheet(
            "#SelectionTable\n"
            "{\n"
            "    border: 4px outset rgba(204, 224, 232, 0.7);\n"
            "    background: rgba(217, 223, 226, 0.8);\n"
            "}\n"
            "QHeaderView::section {\n"
            "    background-color: rgba(204, 224, 232, 0.5);\n"
            " }\n"
            "QTableWidget::item {\n"
            "    font-weight: bold;\n"
            "}"
        )
        self.SelectionTable.setRowCount(0)
        self.SelectionTable.setColumnCount(6)
        self.SelectionTable.setObjectName("SelectionTable")
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SelectionTable.setHorizontalHeaderItem(5, item)
        self.SelectionTable.horizontalHeader().setCascadingSectionResizes(False)
        self.SelectionTable.horizontalHeader().setDefaultSectionSize(90)
        self.SelectionTable.horizontalHeader().setHighlightSections(True)
        self.SelectionTable.horizontalHeader().setSortIndicatorShown(False)
        self.SelectionTable.horizontalHeader().setStretchLastSection(True)
        self.SelectionTable.verticalHeader().setCascadingSectionResizes(False)
        self.SelectionTable.verticalHeader().setHighlightSections(True)
        self.verticalLayout_5.addWidget(self.SelectionTable)
        self.ToolsBox = QtWidgets.QGroupBox(parent=self.Sec2_ToolsWidget)
        self.ToolsBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.ToolsBox.setStyleSheet(
            "#ToolsBox {\n"
            "    width: 100px;\n"
            "    height:100px;\n"
            "    border: 3px solid #1071f0;\n"
            "}"
        )
        self.ToolsBox.setObjectName("ToolsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.ToolsBox)
        self.gridLayout.setContentsMargins(9, 3, 5, 1)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonStart = QtWidgets.QPushButton(parent=self.ToolsBox)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonStart.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.gridLayout.addWidget(self.pushButtonStart, 0, 0, 1, 1)
        self.pushButtonSeg = QtWidgets.QPushButton(parent=self.ToolsBox)
        self.pushButtonSeg.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonSeg.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonSeg.setObjectName("pushButtonSeg")
        self.gridLayout.addWidget(self.pushButtonSeg, 1, 0, 1, 1)
        self.checkBoxSave = QtWidgets.QCheckBox(parent=self.ToolsBox)
        self.checkBoxSave.setStyleSheet("background: rgba(204, 224, 232, 0.5)")
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.gridLayout.addWidget(self.checkBoxSave, 4, 0, 1, 1)
        self.checkBoxSeg = QtWidgets.QCheckBox(parent=self.ToolsBox)
        self.checkBoxSeg.setStyleSheet(
            "\n" "background: rgba(204, 224, 232, 0.5)\n" "\n" "\n" ""
        )
        self.checkBoxSeg.setObjectName("checkBoxSeg")
        self.gridLayout.addWidget(self.checkBoxSeg, 3, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.ToolsBox)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonSave.setStyleSheet(
            "QPushButton {\n"
            "  background-color:#4CAF50;\n"
            "  color: white; \n"
            "  border: 1px solid gray;\n"
            "  border-radius: 7px;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #49c44d, stop: 1 #6cd470);\n"
            "}"
        )
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 2, 0, 1, 1)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(parent=self.ToolsBox)
        self.verticalGroupBox_2.setMouseTracking(False)
        self.verticalGroupBox_2.setTabletTracking(False)
        self.verticalGroupBox_2.setAcceptDrops(False)
        self.verticalGroupBox_2.setAutoFillBackground(False)
        self.verticalGroupBox_2.setStyleSheet(
            "#verticalGroupBox_2 {\n" "border: 2px inset #1071f0;\n" "}"
        )
        self.verticalGroupBox_2.setTitle("")
        self.verticalGroupBox_2.setFlat(False)
        self.verticalGroupBox_2.setCheckable(False)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.verticalGroupBox_2)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.InfTools_ = QtWidgets.QFrame(parent=self.verticalGroupBox_2)
        self.InfTools_.setStyleSheet(
            "#InfTools_\n" "{\n" "border: 0px solid #7C8081;\n" "}"
        )
        self.InfTools_.setObjectName("InfTools_")
        self.InfTools = QtWidgets.QVBoxLayout(self.InfTools_)
        self.InfTools.setContentsMargins(0, 0, 0, 0)
        self.InfTools.setSpacing(5)
        self.InfTools.setObjectName("InfTools")
        self.DataLabel = QtWidgets.QLabel(parent=self.InfTools_)
        self.DataLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.DataLabel.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.DataLabel.setFont(font)
        self.DataLabel.setAutoFillBackground(False)
        self.DataLabel.setStyleSheet(
            "#DataLabel\n"
            "{\n"
            "border: 2px solid #7C8081;\n"
            "background: #D9DFE2;\n"
            "}"
        )
        self.DataLabel.setText("")
        self.DataLabel.setObjectName("DataLabel")
        self.InfTools.addWidget(self.DataLabel)
        self.DataLabel_2 = QtWidgets.QLabel(parent=self.InfTools_)
        self.DataLabel_2.setStyleSheet(
            "#DataLabel_2\n"
            "{\n"
            "border: 2px solid #7C8081;\n"
            "background: #D9DFE2;\n"
            "}"
        )
        self.DataLabel_2.setText("")
        self.DataLabel_2.setObjectName("DataLabel_2")
        self.InfTools.addWidget(self.DataLabel_2)
        self.gridLayout_3.addWidget(self.InfTools_, 0, 2, 3, 1)
        self.SelectionList = QtWidgets.QListWidget(parent=self.verticalGroupBox_2)
        self.SelectionList.setMinimumSize(QtCore.QSize(90, 0))
        self.SelectionList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SelectionList.setMouseTracking(False)
        self.SelectionList.setTabletTracking(False)
        self.SelectionList.setAcceptDrops(False)
        self.SelectionList.setAutoFillBackground(False)
        self.SelectionList.setStyleSheet(
            "#SelectionList\n"
            "{\n"
            "border: 2px solid #7C8081;\n"
            "background: rgba(204, 224, 232, 0.7);\n"
            "}"
        )
        self.SelectionList.setWordWrap(False)
        self.SelectionList.setObjectName("SelectionList")
        self.gridLayout_3.addWidget(self.SelectionList, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalGroupBox_2)
        self.label_2.setStyleSheet(
            "#label_2{\n" " color: white;\n" " background: #717270;\n" " }"
        )
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.verticalGroupBox_2)
        self.label.setStyleSheet(
            "#label{\n" " color: white;\n" " background: #717270;\n" " }"
        )
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.SelectionListSeg = QtWidgets.QListWidget(parent=self.verticalGroupBox_2)
        self.SelectionListSeg.setMinimumSize(QtCore.QSize(90, 0))
        self.SelectionListSeg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SelectionListSeg.setStyleSheet(
            "#SelectionListSeg\n"
            "{\n"
            "border: 2px solid #7C8081;\n"
            "background: rgba(204, 224, 232, 0.7);\n"
            "}"
        )
        self.SelectionListSeg.setObjectName("SelectionListSeg")
        self.gridLayout_3.addWidget(self.SelectionListSeg, 1, 1, 2, 1)
        self.gridLayout.addWidget(self.verticalGroupBox_2, 0, 1, 10, 1)
        self.AccuracyWidget = QtWidgets.QWidget(parent=self.ToolsBox)
        self.AccuracyWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.AccuracyWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.AccuracyWidget.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.PreventContextMenu
        )
        self.AccuracyWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.AccuracyWidget.setAutoFillBackground(False)
        self.AccuracyWidget.setStyleSheet("")
        self.AccuracyWidget.setObjectName("AccuracyWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.AccuracyWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AccuracyText = QtWidgets.QLabel(parent=self.AccuracyWidget)
        self.AccuracyText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.AccuracyText.setStyleSheet("#AccuracyText{ color: white; }")
        self.AccuracyText.setObjectName("AccuracyText")
        self.horizontalLayout_2.addWidget(self.AccuracyText)
        self.AccuracySlider = QtWidgets.QSlider(parent=self.AccuracyWidget)
        self.AccuracySlider.setMouseTracking(False)
        self.AccuracySlider.setTabletTracking(False)
        self.AccuracySlider.setAcceptDrops(False)
        self.AccuracySlider.setAutoFillBackground(False)
        self.AccuracySlider.setMinimum(30)
        self.AccuracySlider.setSingleStep(1)
        self.AccuracySlider.setPageStep(10)
        self.AccuracySlider.setSliderPosition(90)
        self.AccuracySlider.setTracking(True)
        self.AccuracySlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.AccuracySlider.setInvertedAppearance(False)
        self.AccuracySlider.setInvertedControls(False)
        self.AccuracySlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.AccuracySlider.setTickInterval(0)
        self.AccuracySlider.setObjectName("AccuracySlider")
        self.horizontalLayout_2.addWidget(self.AccuracySlider)
        self.gridLayout.addWidget(self.AccuracyWidget, 5, 0, 1, 1)
        self.AccuracyLable = QtWidgets.QLabel(parent=self.ToolsBox)
        self.AccuracyLable.setMinimumSize(QtCore.QSize(0, 0))
        self.AccuracyLable.setMaximumSize(QtCore.QSize(100, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.AccuracyLable.setFont(font)
        self.AccuracyLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AccuracyLable.setObjectName("AccuracyLable")
        self.gridLayout.addWidget(self.AccuracyLable, 6, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.ToolsBox)
        self.gridLayout_2.addWidget(self.Sec2_ToolsWidget, 1, 1, 2, 1)
        self.Sec1_ImageWidget = QtWidgets.QWidget(parent=self.CentralGroupBox)
        self.Sec1_ImageWidget.setStyleSheet(
            "#Sec1_ImageWidget\n"
            "{\n"
            "    border: 4px outset rgba(204, 224, 232, 0);\n"
            "    background: rgba(204, 224, 232, 0);\n"
            "}"
        )
        self.Sec1_ImageWidget.setObjectName("Sec1_ImageWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Sec1_ImageWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.Sec1_ImageWidget)
        self.tabWidget.setStyleSheet(
            "QTabWidget::pane{ \n"
            "    border: 4px outset rgba(204, 224, 232, 0.5);\n"
            "    background: rgba(204, 224, 232, 0);\n"
            "\n"
            "} \n"
            "\n"
            "QTabBar::tab { \n"
            "    border: 4px outset rgba(204, 224, 232, 0.5);\n"
            "    background: rgba(217, 223, 226, 0.8);\n"
            "    padding: 10px;\n"
            "    width: 100%;\n"
            "\n"
            "}\n"
            "\n"
            "QTabBar::tab:selected { \n"
            "    background: #8E979A; \n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            ""
        )
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PlaceForFotos = QtWidgets.QLabel(parent=self.tab)
        self.PlaceForFotos.setStyleSheet(
            "#PlaceForFotos\n" "{\n" "border: 4px inset #10f0ad;\n" "\n" "}"
        )
        self.PlaceForFotos.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.PlaceForFotos.setScaledContents(True)
        self.PlaceForFotos.setObjectName("PlaceForFotos")
        self.verticalLayout_3.addWidget(self.PlaceForFotos)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PlaceForPromFotos = ClickableLabel(parent=self.tab_2)
        self.PlaceForPromFotos.setStyleSheet(
            "#PlaceForPromFotos\n" "{\n" "border: 4px outset #10f0e9;\n" "\n" "}"
        )
        self.PlaceForPromFotos.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.PlaceForPromFotos.setScaledContents(True)
        self.PlaceForPromFotos.setObjectName("PlaceForPromFotos")
        self.verticalLayout_2.addWidget(self.PlaceForPromFotos)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.gridLayout_2.addWidget(self.Sec1_ImageWidget, 1, 2, 2, 1)
        self.verticalLayout.addWidget(self.CentralGroupBox)
        MainWindow.setCentralWidget(self.CentralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FISH data processing"))
        item = self.SelectionTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер клетки"))
        item = self.SelectionTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Центр X"))
        item = self.SelectionTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Центр Y"))
        item = self.SelectionTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Зеленые х-мы"))
        item = self.SelectionTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Красные х-мы"))
        item = self.SelectionTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Тип клетки"))
        self.pushButtonStart.setText(_translate("MainWindow", "Выбрать фото"))
        self.pushButtonSeg.setText(_translate("MainWindow", "Cегментировать"))
        self.checkBoxSave.setText(_translate("MainWindow", "Сохранить все"))
        self.checkBoxSeg.setText(_translate("MainWindow", "Сегментировать все"))
        self.pushButtonSave.setText(_translate("MainWindow", "Сохранить"))
        self.SelectionList.setSortingEnabled(False)
        self.label_2.setText(_translate("MainWindow", "Результат:"))
        self.label.setText(_translate("MainWindow", "Изображения:"))
        self.AccuracyText.setText(_translate("MainWindow", "Порог точности:  "))
        self.AccuracyLable.setText(_translate("MainWindow", "0.9"))
        self.PlaceForFotos.setText(
            _translate(
                "MainWindow", "Исходное изображение, в формате .jpeg, png или .czi"
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Изображение")
        )
        self.PlaceForPromFotos.setText(
            _translate("MainWindow", "Результат сегментации")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Результат")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
